language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master # build master branch only
before_install: 
  - mkdir themes
  - git clone https://github.com/mingwiki/hexo-theme-Chic.git themes/Chic
script:
  - hexo g # generate static files
deploy:
  provider: pages
  cleanup: false
  keep-history: true
  edge: true
  github-token: $GH_TOKEN
  on:
    branch: master
  local-dir: public
  fqdn: journal.zed.ink
notifications:
  email:
    recipients:
      - mingwiki@gmail.com
    on_success: change
    on_failure: always
